TPASPKT-1437 Remove leftover console script entry point
The entry_points/console_scripts registration in setup.py and the
corresponding %{_bindir}/metax_access file entry in the RHEL9 spec
were missed when the CLI was removed long time ago. So metax_access
command was still included in the RPM package, but it failed with error:

	  File "/usr/bin/metax_access", line 5, in <module>
	    from metax_access.__main__ import main
	ModuleNotFoundError: No module named 'metax_access.__main__'